default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['SWAPP_DATABASE_NAME'] %>
  username: <%= ENV['SWAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['SWAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['SWAPP_DATABASE_HOST'] %>
  pool: <%= ENV['SWAPP_DATABASE_POOL'] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: swapp_api_test

production:
  <<: *default
